// src/apps/neon/src/partials/Hero.vue
<template>
  <section class="relative">
    <!-- Background gradient -->
    <div class="absolute inset-0 bg-gradient-to-b from-slate-900 to-slate-800 pointer-events-none -z-10" aria-hidden="true"></div>
    <!-- Illustration -->
    <div class="absolute inset-0 max-w-6xl mx-auto px-4 sm:px-6 -z-10" aria-hidden="true">
      <svg class="absolute inset-y-0 right-0 translate-x-1/2 h-screen text-slate-800" width="1027" height="736" fill="none" viewBox="0 0 1027 736">
        <path d="M1027 0H741.037L579.230 184.475C454.873 286.936 255.857 281.646 137.520 173.111L0 49.398V736H1027V0Z" fill="currentColor" />
      </svg>
    </div>
    
    <div class="max-w-6xl mx-auto px-4 sm:px-6">
      <div class="pt-20 pb-16 md:pt-40 md:pb-20">
        <!-- Hero content -->
        <div class="max-w-3xl mx-auto text-center">
          <div class="mb-6" data-aos="fade-down">
            <div class="inline-flex text-sm font-semibold py-1 px-3 m-2 text-green-600 bg-green-200 rounded-full">Sustainable Energy Investment</div>
          </div>
          <h1 class="text-3xl md:text-5xl lg:text-6xl font-bold text-white mb-6 md:mb-8" data-aos="fade-down">EnergyOne: Power Your Investment Portfolio</h1>
          <div class="max-w-2xl mx-auto mb-8 md:mb-10" data-aos="fade-down" data-aos-delay="150">
            <p class="text-lg md:text-xl text-slate-300">Join thousands of investors funding the renewable energy revolution with our transparent, data-driven platform.</p>
          </div>
          <div class="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-4 mb-12" data-aos="fade-up" data-aos-delay="300">
            <router-link to="/signup" class="btn text-white bg-gradient-to-r from-blue-600 to-blue-400 hover:from-blue-500 hover:to-blue-300 shadow-lg shadow-blue-500/20 rounded-full px-8 py-3 font-semibold w-full sm:w-auto">Create Your Account</router-link>
            <router-link to="/dashboard" class="btn text-slate-300 bg-slate-700/80 hover:bg-slate-600 border-slate-600 rounded-full px-8 py-3 font-semibold w-full sm:w-auto">View Demo Dashboard</router-link>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Hero',
}
</script>

<style scoped>
.btn {
  @apply inline-flex items-center justify-center rounded-lg border border-transparent px-4 py-3 text-base font-medium transition duration-150 ease-in-out;
}
</style>

// src/routes/Hero.svelte
<script>
	import Globe from './Globe.svelte';
</script>

<div class="bg-white" id="hero">
	<div class="relative isolate pt-14">
		<svg
			class="absolute inset-0 -z-10 size-full stroke-gray-200 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]"
			aria-hidden="true">
			<defs>
				<pattern id="83fd4e5a-9d52-42fc-97b6-718e5d7ee527" width="200" height="200" x="50%" y="-1"
								 patternUnits="userSpaceOnUse">
					<path d="M100 200V.5M.5 .5H200" fill="none" />
				</pattern>
			</defs>
			<svg x="50%" y="-1" class="overflow-visible fill-gray-50">
				<path d="M-100.5 0h201v201h-201Z M699.5 0h201v201h-201Z M499.5 400h201v201h-201Z M-300.5 600h201v201h-201Z"
							stroke-width="0" />
			</svg>
			<rect width="100%" height="100%" stroke-width="0" fill="url(#83fd4e5a-9d52-42fc-97b6-718e5d7ee527)" />
		</svg>
		<div class="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:flex lg:items-center lg:gap-x-10 lg:px-8 lg:py-40">
			<div class="mx-auto max-w-2xl lg:mx-0 lg:flex-auto">
				<div class="flex">
				</div>
				<h1 class="mt-10 text-5xl font-semibold tracking-tight text-pretty text-gray-900 sm:text-7xl">Power Your
					Investment Portfolio</h1>
				<p class="mt-8 text-lg font-medium text-pretty text-gray-500 sm:text-xl/8">Join thousands of investors funding
					the renewable energy revolution with our transparent, data-driven platform.</p>
				<div class="mt-10 flex items-center gap-x-6">
					<a href="/signup"
						 class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Get
						started</a>
					<a href="#stats" class="text-sm/6 font-semibold text-gray-900">Learn more <span
						aria-hidden="true">→</span></a>
				</div>
			</div>
			<div class="mt-16 sm:mt-24 lg:mt-0 lg:shrink-0 lg:grow">
				<Globe />
			</div>
		</div>
	</div>
</div>
